<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>New HMTL document by NewJect</title>

    <style>
        table,
        th,
        td {
            border: 1px solid black;
        }

    </style>

</head>

<body>

<div>
    <h3>this is new html document generated by newject extention</h3>
</div>

<?php
$array = array();
//$j = 0;
//for ($i = 0; $i < 30; $i++) {
//    $array[$j][$i] = $i;
//    if (($i + 1) % 10 === 0 & $i !== 0) {
//        $j++;
//    }
//}

for ($i = 0; $i < 3; $i++) {
    for ($j = $i * 10; $j < $i * 10 + 10; $j++) {
        $array[$i][$j] = $j;
    }
}

echo "<table>";
foreach ($array as $row) {
    echo "<tr>";
    foreach ($row as $column) {
        echo "<td>$column</td>";
    }
    echo "</tr>";
}
echo "</table>";

$arrayl = array('one', 'two', 'three', 'four');
echo "<ul>";
for ($i = 0; $i < count($arrayl); $i++) {
    echo "  <li>{$arrayl[$i]}</li>\n";
}
echo "</ul>";
?>

</body>

</html>
